development:
  adapter: postgresql
  encoding: unicode
  database: profile_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: profile_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: profile_production
pool: 5